
user = "shaywoon24"
password = "Iliveinarkansas1"
account = "https://bj23766.us-east-2.aws.snowflakecomputing.com."
warehouse = "compute_wh" 
database = "pc_rivery_db" 
schema = "public"
role= "accountadmin"



