[connections.snowflake]
url = "snowflake://<shaywoon24>@<bj23766>/"

[connections.snowflake.create_engine_kwargs.connect_args]
authenticator = "externalbrowser"
password = "Iliveinarkansas1"
warehouse = "compute_wh" 
database = "pc_rivery_db" 
schema = "public"
role= "accountadmin"
client_session_keep_alive = true


